// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY3FoeXJttBxpdGI8D1YaP8miALmhiA7s',
    appId: '1:803885927964:web:a73793e7051dfe7a3459d9',
    messagingSenderId: '803885927964',
    projectId: 'mybukupink-b758b',
    authDomain: 'mybukupink-b758b.firebaseapp.com',
    storageBucket: 'mybukupink-b758b.appspot.com',
    measurementId: 'G-GLB7027HWK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDSzc6JdvzRy_1hYTac2fyDdv_yCHPyHI',
    appId: '1:803885927964:android:3b9d036f5d470b083459d9',
    messagingSenderId: '803885927964',
    projectId: 'mybukupink-b758b',
    storageBucket: 'mybukupink-b758b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm2cNZdMEVrOc8ZyQtsi0FqsHWOF16gXg',
    appId: '1:803885927964:ios:7e6847a5bae7de273459d9',
    messagingSenderId: '803885927964',
    projectId: 'mybukupink-b758b',
    storageBucket: 'mybukupink-b758b.appspot.com',
    iosBundleId: 'com.example.mybukupink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm2cNZdMEVrOc8ZyQtsi0FqsHWOF16gXg',
    appId: '1:803885927964:ios:5a58cf6dc172ff6f3459d9',
    messagingSenderId: '803885927964',
    projectId: 'mybukupink-b758b',
    storageBucket: 'mybukupink-b758b.appspot.com',
    iosBundleId: 'com.example.mybukupink.RunnerTests',
  );
}
